<?php 

return array(
	'staffsite' => array(
		'hostname' => 'localhost',
		'username' => 'root',
		'password' => 'root',
		'database' => 'inf_staffsite',
		'dbdriver' => 'mysql',
		'dbprefix' => '',
		'pconnect' => TRUE,
		'db_debug' => TRUE,
		'cache_on' => FALSE,
		'cachedir' => '',
		'char_set' => 'utf8',
		'dbcollat' => 'utf8_general_ci',
		'swap_pre' => '',
		'autoinit' => TRUE,
		'stricton' => FALSE,
		),
	'portfolio' => array(
		'hostname' => 'localhost',
		'username' => 'root',
		'password' => 'root',
		'database' => 'inf_portofolio',
		'dbdriver' => 'mysql',
		'dbprefix' => '',
		'pconnect' => TRUE,
		'db_debug' => TRUE,
		'cache_on' => FALSE,
		'cachedir' => '',
		'char_set' => 'utf8',
		'dbcollat' => 'utf8_general_ci',
		'swap_pre' => '',
		'autoinit' => TRUE,
		'stricton' => FALSE,
		),
	);